Libreria/routes/web.php
<?php

use App\Http\Controllers\EditorialController;
use App\Http\Controllers\LibroController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('libro',LibroController::class);
Route::resource('editorial',EditorialController::class);

Libreria/app/Models/Editorial.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Editorial extends Model
{
    use HasFactory;
    protected $fillable=['nombre'];
    public function libros() {
        return $this->hasMany(Libro::class,'editorial_id' , 'id');
    }
}

Libreria/app/Models/Libro.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Libro extends Model
{
    use HasFactory;
    protected $fillable = [
        'titulo', 
        'editorial_id', 
        'edicion', 
        'pais', 
        'precio',
    ];
    public function Editorial()
    {
        return $this->belongsTo(Editorial::class,'editorial_id' , 'id');
    }
}

Libreria/app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

Libreria/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

Libreria/app/Http/Controllers/EditorialController.php
<?php

namespace App\Http\Controllers;

use App\Models\Editorial;
use Illuminate\Http\Request;

class EditorialController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $editorial = Editorial::all();
        return view('libro.index', [
            'editorial' => $editorial
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(Editorial $editorial)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Editorial $editorial)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Editorial $editorial)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Editorial $editorial)
    {
        //
    }
}

Libreria/app/Http/Controllers/LibroController.php
<?php

namespace App\Http\Controllers;

use App\Models\Editorial;
use App\Models\Libro;
use Illuminate\Http\Request;

class LibroController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        
        $libros = Libro::all();
        return view('libro.index', [
            'libros' => $libros
        ]);
        


    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {   $editoriales=Editorial::all();
        return view('libro.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $input = $request->all();
        
        return redirect()->route('libro.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(Libro $libro)
    {
        return view('libro.show',[
            'libro' => $libro
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Libro $libro)
    {
        return view('libro.edit',[
            'libro' => $libro
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Libro $libro)
    {
        $input = $request->all();
        $libro->update($input);
        return  view('libro.show', [
            'libro' => $libro
        ]);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Libro $libro)
    {
        $libro->delete();
        return redirect()->route('libro.index');

    }
}

Libreria/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <!-- Otras etiquetas head -->

    <!-- Agregar Tailwind CSS -->
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.15/dist/tailwind.min.css" rel="stylesheet">
    
</head>
<body class="font-sans bg-gray-100">
    <!-- Barra de navegación -->

    <nav class="bg-blue-500 p-4 text-white">
        <div class="container mx-auto">
            <h1 class="text-2xl font-bold">{{ config('app.name', 'Laravel') }}</h1>
        </div>
    </nav>

    <!-- Contenido principal -->
    <div class="container mx-auto p-4">
        @yield('content')
    </div>

    <!-- Agregar Tailwind CSS y JavaScript (opcional) -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

Libreria/resources/views/libro/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

    <form action="{{ route('libro.store') }}" method="POST">
        @csrf
        <div>
            <label for="titulo">Título</label>
            <input type="text" name="titulo" id="titulo">
        </div>
        <div>
            <label for="editorial_id">Editorial ID</label>
            <input type="number" name="editorial_id" id="editorial_id">
        </div>
        <div>
            <label for="edicion">Edición</label>
            <input type="number" name="edicion" id="edicion">
        </div>
        <div>
            <label for="pais">País</label>
            <input type="text" name="pais" id="pais">
        </div>
        <div>
            <label for="precio">Precio</label>
            <input type="number" name="precio" id="precio" step="0.01">
        </div>
        <div>
            <input type="submit" value="Registrar">
        </div>
    </form>
    
    
</body>
</html>

Libreria/resources/views/libro/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

    <form action="{{ route('libro.update', $libro->id) }}" method="POST">
        @csrf
        @method('PUT')
        <div>
            <label for="titulo">Título</label>
            <input type="text" name="titulo" id="titulo" value="{{ $libro->titulo }}">
        </div>
        <div>
            <label for="editorial_id">Editorial ID</label>
            <input type="number" name="editorial_id" id="editorial_id" value="{{ $libro->editorial_id }}">
        </div>
        <div>
            <label for="edicion">Edición</label>
            <input type="number" name="edicion" id="edicion" value="{{ $libro->edicion }}">
        </div>
        <div>
            <label for="pais">País</label>
            <input type="text" name="pais" id="pais" value="{{ $libro->pais }}">
        </div>
        <div>
            <label for="precio">Precio</label>
            <input type="number" name="precio" id="precio" step="0.01" value="{{ $libro->precio }}">
        </div>
        <div>
            <input type="submit" value="Actualizar">
        </div>
    </form>
    
    
</body>
</html>

Libreria/resources/views/libro/index.blade.php
@extends('layouts.app')

@section('content')
<h1>Listado de libros</h1>
<div class="flex flex-col">
    <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">
            <div class="overflow-hidden">
                <table class="min-w-full text-left text-sm font-light">
                    <thead class="border-b font-medium dark:border-neutral-500">
                        <tr>
                            <th scope="col" class="px-6 py-4">Título</th>
                            <th scope="col" class="px-6 py-4">Editorial</th>
                            <th scope="col" class="px-6 py-4">Edición</th>
                            <th scope="col" class="px-6 py-4">Paígits</th>
                            <th scope="col" class="px-6 py-4">Precio</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($libros as $libro)
                        <tr class="border-b dark:border-neutral-500">
                            <td class="whitespace-nowrap px-6 py-4">{{ $libro->titulo }}</td>
                            <td class="whitespace-nowrap px-6 py-4">{{ $libro->editorial_id}}</td>
                            <td class="whitespace-nowrap px-6 py-4">{{ $libro->edicion }}</td>
                            <td class="whitespace-nowrap px-6 py-4">{{ $libro->pais }}</td>
                            <td class="whitespace-nowrap px-6 py-4">{{ $libro->precio }}</td>
                            <td>
                                <a href="{{ route('libro.show', $libro->id) }}">Mostrar</a>
                                <a href="{{ route('libro.edit', $libro->id) }}">Editar</a>
                            </td>
                            <td>
                                <form action="{{ route('libro.destroy', $libro->id) }}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit">Eliminar</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<a href="{{ route('libro.create') }}">Registrar Libro</a>

@endsection

Libreria/resources/views/libro/inicio.blade.php
@extends('layouts.app')

@section('content')
<h1>Listado de editoriales</h1>
<div class="flex flex-col">
    <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">
            <div class="overflow-hidden">
                <table class="min-w-full text-left text-sm font-light">
                    <thead class="border-b font-medium dark:border-neutral-500">
                        <tr>
                            <th scope="col" class="px-6 py-4">Nombre</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($editoriales as $editorial)
                        <tr class="border-b dark:border-neutral-500">
                            <td class="whitespace-nowrap px-6 py-4">{{ $editorial->nombre }}</td>
                            <td>
                                <a href="{{ route('editorial.show', $editorial->id) }}">Mostrar</a>
                                <a href="{{ route('editorial.edit', $editorial->id) }}">Editar</a>
                            </td>
                            <td>
                                <form action="{{ route('editorial.destroy', $editorial->id) }}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit">Eliminar</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<a href="{{ route('editorial.create') }}">Registrar Editorial</a>

@endsection

Libreria/resources/views/libro/listado.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

    <h1>Listado de libros con {{ $tipo_documento->descripcion }}</h1>
    <table>
        <tr>
            <th>Título</th>
            <th>Editorial</th>
            <th>Edición</th>
            <th>País</th>
            <th>Precio</th>
        </tr>
        @foreach ($libros as $libro)
        <tr>
            <td>{{ $libro->titulo }}</td>
            <td>{{ $libro->editorial_id }}</td>
            <td>{{ $libro->edicion }}</td>
            <td>{{ $libro->pais }}</td>
            <td>{{ $libro->precio }}</td>
            <td>
                <a href="{{ route('libro.show', $libro->id) }}">Mostrar</a>
                <a href="{{ route('libro.edit', $libro->id) }}">Editar</a>
            </td>
            <td>
                <form action="{{ route('libro.destroy', $libro->id) }}" method="post">
                    @csrf
                    @method('DELETE')
                    <button type="submit">Eliminar</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
    
    <a href="{{ route('libro.create') }}">Registrar Libro</a>
    
</body>
</html>

Libreria/resources/views/libro/show.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <ul>
        <li>Título: {{ $libro->titulo }}</li>
        <li>Editorial ID: {{ $libro->editorial_id }}</li>
        <li>Edición: {{ $libro->edicion }}</li>
        <li>País: {{ $libro->pais }}</li>
        <li>Precio: {{ $libro->precio }}</li>
    </ul>
    
    <meta http-equiv="refresh" content="3; url={{ route('libro.index') }}" />
    
</body>
</html>